export const ListingData = [
    {
      id: "1",
      title: "Cozy Apartment in Downtown",
      description: "A beautiful and cozy apartment located in the heart of the city, perfect for tourists and business travelers.",
      imageSrc: "https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6MTEzMTA4NzY0ODgzNzUzNjQzNw%3D%3D/original/1077cfcd-29d5-42b7-adab-19e0b620e492.jpeg?im_w=1200&im_q=highq",
      createdAt:  "2024-09-15",
      category: "Apartment",
      roomCount: 2,
      bathroomCount: 1,
      guestCount: 3,
      locationValue: "New York, USA",
      userId: "user123",
      price: 150,
    },
    {
      id: "2",
      title: "Beachfront Villa with Pool",
      description: "Luxurious beachfront villa with stunning views, a private pool, and direct beach access.",
      imageSrc: "https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6MTEyNjMyMzc5Mzc2MTc3OTEzMg%3D%3D/original/8a39953f-f158-4cc2-a112-aa4079e0fca8.jpeg?im_w=1200&im_q=highq",
      createdAt: "2024-09-10",
      category: "Villa",
      roomCount: 4,
      bathroomCount: 3,
      guestCount: 8,
      locationValue: "Miami, USA",
      userId: "user456",
      price: 500,
    },
    {
      id: "3",
      title: "Mountain Cabin Retreat",
      description: "A peaceful retreat nestled in the mountains with breathtaking views and hiking trails nearby.",
      imageSrc: "https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6MTEzMTA4OTQ5ODA0MDcwMTE4Mw%3D%3D/original/a766e0e9-1e6f-4b88-b8d5-ce12375c6de8.png?im_w=1200&im_q=highq",
      createdAt:"2024-09-10",
      category: "Cabin",
      roomCount: 3,
      bathroomCount: 2,
      guestCount: 6,
      locationValue: "Denver, USA",
      userId: "user789",
      price: 200,
    },
    {
      id: "4",
      title: "Modern Loft in the City",
      description: "A sleek and modern loft offering great amenities, located near top attractions and dining.",
      imageSrc: "https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6MTE4NzE3Nzg1NDA2MjM5NzY2NQ%3D%3D/original/6989d581-3f67-4cd9-8cb6-5f5c226aedc6.png?im_w=1200&im_q=highq",
      createdAt: "2024-08-25" ,
      category: "Loft",
      roomCount: 1,
      bathroomCount: 1,
      guestCount: 2,
      locationValue: "San Francisco, USA",
      userId: "user101",
      price: 300,
    },
    {
      id: "5",
      title: "Luxury Penthouse with Skyline View",
      description: "Experience luxury in this penthouse with panoramic skyline views and a private terrace.",
      imageSrc: "https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6MTE3NzY2MTYzNDg4MjE2ODY1Nw%3D%3D/original/a332d020-4315-4f63-af71-444d46474939.png?im_w=1200&im_q=highq",
      createdAt:  "2024-09-05",
      category: "Penthouse",
      roomCount: 3,
      bathroomCount: 3,
      guestCount: 6,
      locationValue: "Chicago, USA",
      userId: "user202",
      price: 750,
    },
    {
      id: "6",
      title: "Charming Cottage Near the Lake",
      description: "A charming and rustic cottage located near a peaceful lake, ideal for a relaxing getaway.",
      imageSrc: "https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6MTEyNjIzMTk3NDU3MjE4Nzg2NA%3D%3D/original/f4cbe542-3ce0-4c6f-a8f1-d2120c1b2420.jpeg?im_w=1200&im_q=highq",
      createdAt: "2024-09-12",
      category: "Cottage",
      roomCount: 2,
      bathroomCount: 1,
      guestCount: 4,
      locationValue: "Lake Tahoe, USA",
      userId: "user303",
      price: 180,
    },
    {
      id: "7",
      title: "Spacious Farmhouse with Garden",
      description: "A spacious farmhouse with a large garden, perfect for family vacations and outdoor activities.",
      imageSrc: "https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6MTEzMTA4NjI3OTI1MjIxNDQyOA%3D%3D/original/bc989f2d-eca8-4bcf-a9b0-b70b8e685a64.jpeg?im_w=1200&im_q=highq",
      createdAt: "2024-09-18",
      category: "Farmhouse",
      roomCount: 5,
      bathroomCount: 4,
      guestCount: 10,
      locationValue: "Austin, USA",
      userId: "user404",
      price: 400,
    },
    {
      id: "8",
      title: "Studio Apartment in Trendy Neighborhood",
      description: "A modern studio apartment located in a trendy neighborhood, ideal for solo travelers or couples.",
      imageSrc: "https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6MTE2MjI1MjI0NDQ0MzYzMjM4Mg%3D%3D/original/ae3426d1-fba4-44d4-bed2-690426f25f7a.jpeg?im_w=1200&im_q=highq",

      createdAt: "2024-08-30",
      category: "Studio",
      roomCount: 1,
      bathroomCount: 1,
      guestCount: 2,
      locationValue: "Los Angeles, USA",
      userId: "user505",
      price: 120,
    },
    {
      id: "9",
      title: "Secluded Treehouse in the Forest",
      description: "A unique treehouse experience deep in the forest, perfect for nature lovers seeking adventure.",
      imageSrc: "https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6MTEyNTQ0NTEyMzEwMTI3NDg1MQ%3D%3D/original/bd73f0f8-9057-4bbc-ad70-1db13eb5c03f.png?im_w=1200&im_q=highq",

      createdAt: "2024-09-22",
      category: "Treehouse",
      roomCount: 1,
      bathroomCount: 1,
      guestCount: 2,
      locationValue: "Portland, USA",
      userId: "user606",
      price: 220,
    },
    {
      id: "10",
      title: "Historic Mansion in the Countryside",
      description: "A grand historic mansion offering luxury and tranquility in the countryside with beautiful gardens.",
      imageSrc: "https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6MTE0ODQ2MDI1NTE4MDMzOTQ4MQ%3D%3D/original/c92634d0-4964-439a-905d-b9129af14d34.jpeg?im_w=1200&im_q=highq",
      createdAt: "2024-09-08",
      category: "Mansion",
      roomCount: 7,
      bathroomCount: 5,
      guestCount: 14,
      locationValue: "Nashville, USA",
      userId: "user707",
      price: 1000,
    },
  ];
 